// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-10-08 16:42:35.233742 +0800 CST m=+0.287921875

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Tronscan API",
        "title": "Tronscan",
        "contact": {
            "name": "tron"
        },
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/api/stats/overview": {
            "get": {
                "description": "Query statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Query statistics",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":[{\"date\":1529884800000,\"totalTransaction\":3084,\"avgBlockTime\":3,\"avgBlockSize\":197,\"totalBlockCount\":26548,\"newAddressSeen\":2179,\"blockchainSize\":5243100,\"totalAddress\":2208,\"newBlockSeen\":26547,\"newTransactionSeen\":3081}...]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/witness": {
            "get": {
                "description": "Query witness",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Witness"
                ],
                "summary": "Query witness",
                "responses": {
                    "200": {
                        "description": "[{\"address\":\"TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp\",\"name\":\"Sesameseed\",\"url\":\"https://www.sesameseed.org\",\"producer\":true,\"latestBlockNumber\":3021119,\"latestSlotNumber\":512995842,\"missedTotal\":232,\"producedTotal\":94778,\"producedTrx\":0,\"votes\":694559265,\"producePercentage\":99.75521745552766,\"votesPercentage\":8.503402454074505}...]",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/witness/maintenance-statistic": {
            "get": {
                "description": "Query witness statistic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Witness"
                ],
                "summary": "Query witness statistic",
                "responses": {
                    "200": {
                        "description": "[{\"address\":\"TBXB5tobBPCFkC8ihFDBWjaiwW2iSpzSfr\",\"name\":\"TRONVIETNAM\",\"url\":\"https://www.tronvietnam.com/\",\"blockProduced\":115,\"total\":3106,\"percentage\":0.037}...]",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
