info:
  contact:
    name: tron
  description: Tronscan API
  license: {}
  title: Tronscan
  version: "1.0"
paths:
  /api/stats/overview:
    get:
      consumes:
      - application/json
      description: Query statistics
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":[{"date":1529884800000,"totalTransaction":3084,"avgBlockTime":3,"avgBlockSize":197,"totalBlockCount":26548,"newAddressSeen":2179,"blockchainSize":5243100,"totalAddress":2208,"newBlockSeen":26547,"newTransactionSeen":3081}...]}'
          schema:
            type: string
      summary: Query statistics
      tags:
      - statistics
  /api/witness:
    get:
      consumes:
      - application/json
      description: Query witness
      produces:
      - application/json
      responses:
        "200":
          description: '[{"address":"TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp","name":"Sesameseed","url":"https://www.sesameseed.org","producer":true,"latestBlockNumber":3021119,"latestSlotNumber":512995842,"missedTotal":232,"producedTotal":94778,"producedTrx":0,"votes":694559265,"producePercentage":99.75521745552766,"votesPercentage":8.503402454074505}...]'
          schema:
            type: string
      summary: Query witness
      tags:
      - Witness
  /api/witness/maintenance-statistic:
    get:
      consumes:
      - application/json
      description: Query witness statistic
      produces:
      - application/json
      responses:
        "200":
          description: '[{"address":"TBXB5tobBPCFkC8ihFDBWjaiwW2iSpzSfr","name":"TRONVIETNAM","url":"https://www.tronvietnam.com/","blockProduced":115,"total":3106,"percentage":0.037}...]'
          schema:
            type: string
      summary: Query witness statistic
      tags:
      - Witness
swagger: "2.0"
